'use client'

import { useEffect, useState } from "react"
import { getUser } from "@/lib/auth"
import { createClient } from "@/utils/supabase/client"
import Track from './Track'

const TrackSection = () => {
    const [data, setData] = useState<any[]>([])
    const [user, setUser] = useState<any>(null)
    const [loading, setLoading] = useState(false)

    useEffect(() => {
        // Check user on mount
        getTracks()

        // Listen for auth changes
        const supabase = createClient()
        const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
            setUser(session?.user ?? null)
        })

        return () => subscription.unsubscribe()
    }, [])

    // Log when data state changes
    useEffect(() => {
        console.log('Data state changed to:', data)
    }, [data])

    const getTracks = async () => {
        try {
            setLoading(true)
            const currentUser = await getUser()
            setUser(currentUser)

            if (!currentUser) {
                console.log('No user found')
                return
            }

            console.log('User ID:', currentUser.id)
            
            const supabase = createClient()
            
            // Step 1: Get user's track IDs from user_tracks
            const { data: userTracksData, error: userTracksError } = await supabase
                .from('user_tracks')
                .select('track_id')
                .eq('user_id', currentUser.id)
            
            // console.log('User tracks data:', userTracksData)
            
            if (userTracksError) {
                console.error('Error fetching user tracks:', userTracksError)
                return
            }

            if (!userTracksData || userTracksData.length === 0) {
                console.log('No tracks found for this user')
                setData([])
                return
            }

            // Step 2: Extract track IDs
            const trackIds = userTracksData.map((ut: any) => ut.track_id)
            // console.log('Track IDs to fetch:', trackIds)

            // Step 3: Get full track details from tracks table
            const { data: tracksData, error: tracksError } = await supabase
                .from('tracks')
                .select('*')
                .in('id', trackIds)
            
            // console.log('Full tracks data:', tracksData)
            
            if (tracksError) {
                console.error('Error fetching tracks:', tracksError)
                return
            }

            setData(tracksData || [])

        } catch (error) {
            console.log('Catch block error:', error)
        } finally {
            setLoading(false)
        }
    }


    return (
        <>
            <div className="px-16 py-6 flex justify-center">
                <div className="flex flex-col max-w-7xl p-16 w-full rounded-2xl bg-white shadow-lg overflow-hidden">
                    <h1 className="text-2xl font-bold mb-4">Your Credits</h1>
                    <div className="flex flex-col gap-4">
                        {data.map((track) => (
                            <Track 
                                key={track.id}
                                track_name={track.track_name} 
                                album_name={track.album_name} 
                                created_at={track.created_at} 
                                artist_name={track.artist_name}
                                popularity = {track.popularity}
                                streams = {track.spotify_streams}
                                release_date = {track.release_date}
                                image_url = {track.image_url}
                            />
                        ))}
                    </div>
                </div>
            </div>
        </>
    )
}

export default TrackSection;

// create table public.user_tracks (
//     id bigint generated by default as identity not null,
//     created_at timestamp with time zone not null default now(),
//     track_id bigint not null,
//     user_id text not null,
//     constraint user_tracks_pkey primary key (id),
//     constraint user_tracks_track_id_fkey foreign KEY (track_id) references tracks (id)
//   ) TABLESPACE pg_default;

//   create table public.tracks (
//     id bigint generated by default as identity not null,
//     created_at timestamp with time zone not null default now(),
//     track_name text null,
//     popularity bigint null,
//     artist_name text null,
//     track_genre text null,
//     track_length bigint null,
//     track_id text not null default '1'::text,
//     album_name text null,
//     constraint tracks_pkey primary key (id)
//   ) TABLESPACE pg_default;

